AllCops:
  Exclude:
    - Gemfile
    - tmp/**/*
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.2
Rails:
  Enabled: true
LineLength:
  Max: 120
Documentation:
  Enabled: false
