# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b2a2b68a56b3fca6008d574e70ddcfc30d31a7627d2e767b1f55100221f295c35c4a6d9384471db36108153c1efcca37639de19f5e16fbb6a4dca3c9be216c0

test:
  secret_key_base: 45f598a3ffe78654b177c6a2a99d0992a8cfe54c0b60f0cf5b8fe3e0f7ebedbf57855f33becd76683193aa84f313685bcdaf903074e3cf6899ffffc7d7e9cae0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
